name: Makefile CI
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: make

      - name: Test
        run: npm run test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm i

      - name: Format
        run: npx prettier --config .prettierrc 'src/**/*' -c
