name: Makefile CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ankiaddon-file
          path: |
            searchStatsExtended.ankiaddon

      - name: Test
        run: npm run test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm i

      - name: Format
        run: npx prettier --config .prettierrc 'src/**/*' -c
