name: Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: make

      - name: Upload release assets
        run: |
          gh release upload ${{ github.event.release.tag_name }} searchStatsExtended.ankiaddon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}